"""abex_canvas.py — the design's screens, as data. GENERATED, do not hand-edit.

Extracted verbatim from the Claude Design canvas, which encodes every screen the
way the spec describes it in §4:

    screen = {d, title, asof, band?, band3?, blocks[], dock?}
    block  = {h2, ac?, own?} + one of
             table   : c[headers], r[rows], n?(note), lk?(link)
             balance : bal[[label, value, note]], tot?(ruled total row)
             action  : act(sentence), btns[[label, 'p'|'s'|'d']]

Regenerate with `python tools/canvas_to_py.py <canvas.dc.html> abex_canvas.py`.

The ROWS are the design's sample data, on purpose: each screen is swapped to
live queries one at a time, and until then its SHAPE is still right — columns,
tone rules and copy all correct.

Tone tags on a cell (`g|`, `l|`, `w|`, `m|`, `k|`) mean gain / loss / warn /
faint / action; `G|` on a grade cell asks for the grade ramp.
"""
from __future__ import annotations

SCREENS: dict[str, dict] = {'hub': {'d': 'hub',
         'title': 'Hub',
         'asof': 'Sunday 23 August, 14:10 · next report is BNL on Tuesday 25 August',
         'band': [['Index', '1,284.6', 'up 2.1% this cycle', 'g'],
                  ['Dividends', '214.60c', '228c estimated next cycle'],
                  ['Holdings', '21,084c', '3,846c unrealised', 'g'],
                  ['Next report', 'Tue 25 Aug', 'BNL, then Amazonia Wed 26 Aug']],
         'blocks': [{'h2': 'Today',
                     'ac': 1,
                     'c': ['What is waiting', 'Who can act', '#'],
                     'r': [['Blaze rod for Nether market, 2 stacks at 180c per stack',
                            'm|Employees only, 8 minutes left',
                            'k|Claim'],
                           ['Iron ingot for Toolshop, 8 stacks at 42c per stack',
                            'm|Employees only, 31 minutes left',
                            'k|Claim'],
                           ['Glass pane for ViridianMarket, 320 pieces at 1.4c per piece',
                            'g|Open to all',
                            'k|Claim'],
                           ['August report for GreyHames', 'm|Due Saturday 29 August', 'k|Open'],
                           ['k|Three unread messages', 'm|Latest Saturday 22 August', '']],
                     'n': 'Five items waiting, soonest first.',
                     'lk': 'All seven open jobs'},
                    {'h2': 'Markets by grade',
                     'c': ['Market', 'Grade', 'Backing#', 'Last net#', 'You hold#', 'Next report'],
                     'r': [['GreyHames', 'G|AAA', '1.70×', '42,180c', '1,240', 'Sat 29 Aug'],
                           ['V Tech', 'G|AA', '1.31×', '24,900c', '260', 'Fri 28 Aug'],
                           ['Amazonia', 'G|AA', '1.28×', '31,050c', '880', 'Wed 26 Aug'],
                           ['Sancta', 'G|AA', '1.24×', '27,600c', '410', 'Thu 3 Sep'],
                           ['NauticalMarket', 'G|A', '1.08×', '15,220c', 'm|—', 'Sun 6 Sep'],
                           ['Nether market', 'G|A', '1.05×', '16,700c', '300', 'Tue 1 Sep'],
                           ['BNL', 'G|A', '1.02×', '18,400c', '1,600', 'Tue 25 Aug']],
                     'n': 'Seven of thirteen markets, best grade first.',
                     'lk': 'How grades are set'},
                    {'h2': 'Dividends',
                     'bal': [['Confirmed, last cycle', '214.60c', ''],
                             ['Estimated, next cycle',
                              '228c',
                              'a figure is only confirmed once that market files']],
                     'lk': 'How estimates work'}]},
 'banking': {'d': 'banking',
             'title': 'Banking',
             'asof': 'Sunday 23 August, 14:10 · interest is paid weekly, on Sundays',
             'band': [['Available', '84,230c', '12,400c held in orders, bids and bets'],
                      ['Savings', '156,900c', 'Veteran rank, 0.20% a week'],
                      ['Interest last week',
                       '313.80c',
                       'paid on principal, not on the coin balance',
                       'g'],
                      ['Available to borrow', '18,000c', '26,000c limit, 8,000c drawn']],
             'blocks': [{'h2': 'Waiting on you',
                         'ac': 1,
                         'c': ['What is due', 'Amount#', 'Due', 'Note'],
                         'r': [['Loan repayment to Overhaul-A-Ledger',
                                'l|1,150c',
                                'Wed 26 Aug',
                                'm|five payments left']],
                         'n': 'One payment due. Missed payments take your savings and bond payouts '
                              'after a three-day grace. Never your wallet.'},
                        {'h2': 'Accounts',
                         'bal': [['Wallet available', '84,230c', ''],
                                 ['Held in orders, bids and bets',
                                  '12,400c',
                                  'six orders, two bids, three bets'],
                                 ['Savings principal', '156,900c', '']],
                         'tot': ['Cash and savings', '253,530c']},
                        {'h2': 'Savings interest',
                         'c': ['Week ending', 'Rank', 'Rate#', 'Principal#', 'Interest paid#'],
                         'r': [['Sun 23 Aug', 'Veteran', '0.20% a week', '156,900c', 'g|313.80c'],
                               ['Sun 16 Aug', 'Veteran', '0.20% a week', '154,100c', 'g|308.20c'],
                               ['Sun 9 Aug', 'Veteran', '0.20% a week', '151,400c', 'g|302.80c'],
                               ['Sun 2 Aug', 'Worker', '0.10% a week', '149,000c', 'g|149.00c']],
                         'n': 'Four most recent weeks. The base rate is 0.07% a week and your rank '
                              'replaces it when it pays more.'},
                        {'h2': 'Debt',
                         'c': ['Loan',
                               'Drawn#',
                               'Rate#',
                               'Repayment#',
                               'Next payment',
                               'Payments left#'],
                         'r': [['Loan from Overhaul-A-Ledger',
                                '8,000c',
                                '1.5% a week',
                                '1,150c',
                                'Wed 26 Aug',
                                '5']],
                         'n': 'One loan. Collections take savings and bond payouts, never the '
                              'wallet, and there is no seizure of shares or land.'},
                        {'h2': 'Credit limit',
                         'bal': [['Base limit', '12,000c', ''],
                                 ['Clean repayments, fourteen at 1,000c',
                                  '14,000c',
                                  'capped at 26,000c'],
                                 ['Less drawn', '8,000c', '']],
                         'tot': ['Available to borrow', '18,000c'],
                         'lk': 'How the limit is earned'}]},
 'stocks': {'d': 'exchange',
            'title': 'Share filings',
            'asof': 'Sunday 23 August, 14:10 · eight of thirteen markets have filed this cycle',
            'band': [['Holdings', '21,084c', '3,846c unrealised', 'g'],
                     ['Dividends', '214.60c', '228c estimated next cycle'],
                     ['Filed this cycle', '8 of 13', 'one missed, four have yet to file'],
                     ['Index', '1,284.6', 'up 2.1% this cycle', 'g']],
            'blocks': [{'h2': 'Filings this cycle',
                        'ac': 1,
                        'c': ['Market',
                              'Filed',
                              'Net for the month#',
                              'Share price#',
                              'Change#',
                              'Dividend a share#',
                              'Grade'],
                        'r': [['Amazonia',
                               'Fri 21 Aug',
                               '31,050c',
                               '4.05c',
                               'g|up 0.14c',
                               '0.05c',
                               'AA'],
                              ['Sancta',
                               'Thu 20 Aug',
                               '27,600c',
                               '3.80c',
                               'g|up 0.06c',
                               '0.04c',
                               'AA'],
                              ['V Tech',
                               'Wed 19 Aug',
                               '24,900c',
                               '5.20c',
                               'l|down 0.11c',
                               '0.05c',
                               'AA'],
                              ['Nether market',
                               'Tue 18 Aug',
                               '16,700c',
                               '3.10c',
                               'g|up 0.08c',
                               '0.04c',
                               'A'],
                              ['Toolshop',
                               'Mon 17 Aug',
                               '12,050c',
                               '1.95c',
                               'l|down 0.04c',
                               '0.01c',
                               'BBB'],
                              ['NauticalMarket',
                               'Sun 16 Aug',
                               '15,220c',
                               '2.60c',
                               'g|up 0.02c',
                               '0.02c',
                               'A'],
                              ['ViridianMarket',
                               'Sat 15 Aug',
                               '9,480c',
                               '1.40c',
                               'm|no change',
                               'm|none',
                               'BBB'],
                              ['Redstone Works',
                               'Fri 14 Aug',
                               '8,120c',
                               '0.95c',
                               'l|down 0.03c',
                               '0.01c',
                               'BBB'],
                              ['Farmstead Co',
                               'l|did not file',
                               'm|—',
                               '0.31c',
                               'm|price held',
                               'm|none',
                               'C']],
                        'n': 'Eight filings and one miss, most recent first. A missed filing keeps '
                             'the last price, pays no dividend and drops a band.'},
                       {'h2': 'Your positions',
                        'c': ['Market',
                              'Shares#',
                              'Price#',
                              'Value#',
                              'Cost#',
                              'Unrealised#',
                              'Dividend last cycle#'],
                        'r': [['GreyHames',
                               '1,240',
                               '6.40c',
                               '7,936.00c',
                               '6,200.00c',
                               'g|1,736.00c',
                               '74.40c'],
                              ['BNL',
                               '1,600',
                               '2.85c',
                               '4,560.00c',
                               '3,600.00c',
                               'g|960.00c',
                               '48.00c'],
                              ['Amazonia',
                               '880',
                               '4.05c',
                               '3,564.00c',
                               '3,050.00c',
                               'g|514.00c',
                               '44.00c'],
                              ['Sancta',
                               '410',
                               '3.80c',
                               '1,558.00c',
                               '1,420.00c',
                               'g|138.00c',
                               '16.40c'],
                              ['V Tech',
                               '260',
                               '5.20c',
                               '1,352.00c',
                               '1,480.00c',
                               'l|128.00c',
                               '13.00c'],
                              ['Toolshop',
                               '538',
                               '1.95c',
                               '1,049.10c',
                               '580.00c',
                               'g|469.10c',
                               '5.38c'],
                              ['Nether market',
                               '300',
                               '3.10c',
                               '930.00c',
                               '780.00c',
                               'g|150.00c',
                               '12.00c'],
                              ['Redstone Works',
                               '142',
                               '0.95c',
                               '134.90c',
                               '128.00c',
                               'g|6.90c',
                               '1.42c']],
                        'n': 'Eight positions in thirteen markets, largest first, at Sunday 23 '
                             'August prices.'},
                       {'h2': 'Portfolio',
                        'bal': [['Value', '21,084.00c', 'at Sunday prices'],
                                ['Less cost', '17,238.00c', '']],
                        'tot': ['Unrealised', '3,846.00c'],
                        'n': 'Dividends confirmed last cycle, 214.60c.',
                        'lk': 'How share prices are set'}]},
 'filing': {'d': 'exchange',
            'title': 'August report, GreyHames',
            'asof': 'Due Saturday 29 August · not yet filed',
            'band3': 1,
            'band': [['Net for the month', '42,180c', 'revenue less stock, costs and pay'],
                     ['Share price if filed', '6.62c', 'up 0.22c from 6.40c', 'g'],
                     ['Grade if filed', 'AAA', '1.70× backed']],
            'blocks': [{'h2': 'File the report',
                        'ac': 1,
                        'own': 1,
                        'act': 'Filing settles the share price, pays the dividend and re-scores '
                               'the grade. It cannot be undone.',
                        'btns': [['File the August report', 'p'], ['Save as draft', 's']],
                        'n': 'A missed filing keeps the last price, pays no dividend and drops a '
                             'band.'},
                       {'h2': 'The figures you are filing',
                        'bal': [['Revenue', '68,940c', '214 ledger entries'],
                                ['Less stock and costs', '18,220c', ''],
                                ['Less worker pay', '8,540c', 'three workers']],
                        'tot': ['Net for the month', '42,180c']},
                       {'h2': 'How the price is set',
                        'bal': [['June net', '36,400c', ''],
                                ['July net', '39,900c', ''],
                                ['August net', '42,180c', ''],
                                ['Trailing mean of three reports', '39,493c', ''],
                                ['Multiplied by growth P/E', '2.01×', ''],
                                ['Divided by shares outstanding',
                                 '12,000',
                                 'book value floor is 4.10c a share']],
                        'tot': ['Share price if filed', '6.62c'],
                        'lk': 'How share prices are set'},
                       {'h2': 'What filing pays',
                        'own': 1,
                        'bal': [['Net for the month', '42,180c', ''],
                                ['Less vault, 10% retained', '4,218c', 'no arrears'],
                                ['Less debt service and bond coupons',
                                 '740c',
                                 'paid before dividends'],
                                ['Less dividend, 0.06c a share', '720c', '12,000 shares']],
                        'tot': ['To the owner', '36,502c'],
                        'lk': 'How the payout order works'},
                       {'h2': 'Last three filings',
                        'c': ['Month',
                              'Filed',
                              'Net#',
                              'Price after#',
                              'Dividend a share#',
                              'Grade'],
                        'r': [['July', 'Fri 25 Jul', '39,900c', '6.40c', '0.06c', 'AAA'],
                              ['June', 'Wed 25 Jun', '36,400c', '6.18c', '0.05c', 'AA'],
                              ['May', 'Mon 26 May', '31,200c', '5.74c', '0.05c', 'AA']],
                        'n': 'Three most recent filings, newest first.'}]},
 'markets': {'d': 'markets',
             'title': 'Markets',
             'asof': 'Sunday 23 August, 14:10 · five markets file in the next seven days',
             'band': [['Markets', '13', 'twelve listed, one private'],
                      ['Index', '1,284.6', 'up 2.1% this cycle', 'g'],
                      ['Investment grade', '10 of 13', 'BBB or better, 0.60× backed'],
                      ['Next filing', 'Tue 25 Aug', 'BNL']],
             'blocks': [{'h2': 'Filing next',
                         'ac': 1,
                         'c': ['Market', 'Files', 'Grade', 'Backing#', 'Last net#', 'You hold#'],
                         'r': [['BNL', 'Tue 25 Aug', 'A', '1.02×', '18,400c', '1,600'],
                               ['Amazonia', 'Wed 26 Aug', 'AA', '1.28×', '31,050c', '880'],
                               ['Redstone Works', 'Thu 27 Aug', 'BBB', '0.64×', '8,120c', '142'],
                               ['V Tech', 'Fri 28 Aug', 'AA', '1.31×', '24,900c', '260'],
                               ['GreyHames', 'Sat 29 Aug', 'AAA', '1.70×', '42,180c', '1,240']],
                         'n': 'Five markets file in the next seven days, soonest first.'},
                        {'h2': 'All thirteen markets',
                         'c': ['Market',
                               'Grade',
                               'Backing#',
                               'Last net#',
                               'Shares out#',
                               'Share price#',
                               'You hold#',
                               'Disclosure',
                               'Next report'],
                         'r': [['GreyHames',
                                'G|AAA',
                                '1.70×',
                                '42,180c',
                                '12,000',
                                '6.40c',
                                '1,240',
                                'Listed',
                                'Sat 29 Aug'],
                               ['V Tech',
                                'G|AA',
                                '1.31×',
                                '24,900c',
                                '6,000',
                                '5.20c',
                                '260',
                                'Listed',
                                'Fri 28 Aug'],
                               ['Amazonia',
                                'G|AA',
                                '1.28×',
                                '31,050c',
                                '9,000',
                                '4.05c',
                                '880',
                                'Listed',
                                'Wed 26 Aug'],
                               ['Sancta',
                                'G|AA',
                                '1.24×',
                                '27,600c',
                                '8,000',
                                '3.80c',
                                '410',
                                'Listed',
                                'Thu 3 Sep'],
                               ['NauticalMarket',
                                'G|A',
                                '1.08×',
                                '15,220c',
                                '7,000',
                                '2.60c',
                                'm|—',
                                'Listed',
                                'Sun 6 Sep'],
                               ['Nether market',
                                'G|A',
                                '1.05×',
                                '16,700c',
                                '6,500',
                                '3.10c',
                                '300',
                                'Listed',
                                'Tue 1 Sep'],
                               ['BNL',
                                'G|A',
                                '1.02×',
                                '18,400c',
                                '9,500',
                                '2.85c',
                                '1,600',
                                'Listed',
                                'Tue 25 Aug'],
                               ['Toolshop',
                                'G|BBB',
                                '0.94×',
                                '12,050c',
                                '7,500',
                                '1.95c',
                                '538',
                                'Listed',
                                'Mon 31 Aug'],
                               ['ViridianMarket',
                                'G|BBB',
                                '0.71×',
                                '9,480c',
                                '8,000',
                                '1.40c',
                                'm|—',
                                'Listed',
                                'Wed 2 Sep'],
                               ['Redstone Works',
                                'G|BBB',
                                '0.64×',
                                '8,120c',
                                '10,000',
                                '0.95c',
                                '142',
                                'Listed',
                                'Thu 27 Aug'],
                               ['Enderport',
                                'G|BB',
                                '0.52×',
                                '6,300c',
                                '5,000',
                                '0.88c',
                                'm|—',
                                'Listed',
                                'Sat 5 Sep'],
                               ['Hollow Bell',
                                'G|BB',
                                '0.44×',
                                'm|—',
                                'm|—',
                                'm|—',
                                'm|—',
                                'Private',
                                'm|—'],
                               ['Farmstead Co',
                                'G|CCC',
                                '0.21×',
                                '1,940c',
                                '4,000',
                                '0.31c',
                                'm|—',
                                'Listed',
                                'l|missed Fri 14 Aug']],
                         'n': 'Thirteen markets, best grade first. Hollow Bell is private and '
                              'shows its ledger to its owner only. A market below BBB cannot issue '
                              'bonds.',
                         'lk': 'How grades are set'}]},
 'market': {'d': 'mymarket',
            'title': 'GreyHames',
            'asof': 'Listed market · you are the owner · August report due Saturday 29 August',
            'band': [['Grade', 'AAA', '1.70× backed'],
                     ['Net last month', '42,180c', 'up 5.7% on July', 'g'],
                     ['Share price', '6.40c', '6.62c if you file today', 'g'],
                     ['Vault', '18,400c', '10% retained, no arrears']],
            'blocks': [{'h2': 'Waiting on you',
                        'ac': 1,
                        'own': 1,
                        'act': 'The August report is due Saturday 29 August. Filing settles the '
                               'share price, pays the dividend and re-scores the grade. It cannot '
                               'be undone.',
                        'btns': [['Open the August report', 'p'], ['Approve three claims', 's']],
                        'n': '1,860c of worker pay is claimed and waiting on approval.'},
                       {'h2': 'Ledger, August',
                        'c': ['Date', 'Entry', 'Category', 'In#', 'Out#'],
                        'r': [['Sat 22 Aug', 'Diamond block, 12 sold', 'Sales', 'g|4,800c', 'm|—'],
                              ['Fri 21 Aug', 'Worker pay, Kael', 'Wages', 'm|—', 'l|1,280c'],
                              ['Fri 21 Aug',
                               'Redstone restock, 6 stacks at 384c per stack',
                               'Stock',
                               'm|—',
                               'l|2,304c'],
                              ['Thu 20 Aug', 'Netherite ingot, 3 sold', 'Sales', 'g|7,200c', 'm|—'],
                              ['Thu 20 Aug', 'Coupon, series A', 'Debt service', 'm|—', 'l|90c'],
                              ['Wed 19 Aug',
                               'Enchanted book, 9 sold at 290c per piece',
                               'Sales',
                               'g|2,610c',
                               'm|—'],
                              ['Wed 19 Aug',
                               'Glass pane restock, 5 stacks at 90c per stack',
                               'Stock',
                               'm|—',
                               'l|450c'],
                              ['Tue 18 Aug',
                               'Iron ingot, 40 stacks sold at 42c per stack',
                               'Sales',
                               'g|1,680c',
                               'm|—']],
                        'n': 'Eight most recent entries of 214 this month, newest first.',
                        'lk': 'The full August ledger'},
                       {'h2': 'August so far',
                        'bal': [['Revenue', '68,940c', ''],
                                ['Less stock and costs', '18,220c', ''],
                                ['Less worker pay', '8,540c', '']],
                        'tot': ['Net for the month', '42,180c']},
                       {'h2': 'Where the net goes',
                        'own': 1,
                        'bal': [['Net for the month', '42,180c', ''],
                                ['Less vault, 10% retained',
                                 '4,218c',
                                 'arrears would cap the grade at BBB'],
                                ['Less debt service and bond coupons',
                                 '740c',
                                 'paid before dividends'],
                                ['Less dividends to shareholders', '720c', '0.06c a share']],
                        'tot': ['To the owner', '36,502c'],
                        'lk': 'How the payout order works'},
                       {'h2': 'Liabilities',
                        'own': 1,
                        'c': ['Item', 'Held by', 'Amount#', 'Due', 'Note'],
                        'r': [['GEX principal',
                               'Abex Tech',
                               '12,000c',
                               'Mon 30 Nov',
                               'm|a debt claim, not equity'],
                              ['Bonds, series A',
                               'six holders',
                               '10,000c',
                               'Fri 27 Nov',
                               'm|0.9% a month, 90c coupon'],
                              ['Bonds, series B',
                               'three holders',
                               '5,000c',
                               'Wed 30 Sep',
                               'm|1.0% a month, 50c coupon'],
                              ['Worker pay owed',
                               'three workers',
                               '1,860c',
                               'Fri 28 Aug',
                               'm|claimed, awaiting approval']],
                        'n': 'Four liabilities, 28,860c in total. A listed market discloses its '
                             'ledger, staff and liabilities.'},
                       {'h2': 'Staff',
                        'own': 1,
                        'c': ['Worker', 'Role', 'Orders filled#', 'Paid this month#', 'Owed#'],
                        'r': [['Kael', 'Employee', '34', '4,220c', 'w|620c'],
                              ['Mira', 'Employee', '21', '2,610c', 'w|740c'],
                              ['Bram', 'Casual', '12', '1,710c', 'w|500c']],
                        'n': 'Three workers, 8,540c paid this month. Pay is per piece unless the '
                             'order says per stack; a stack is 64.'}]},
 'exchange': {'d': 'exchange',
              'title': 'Exchange',
              'asof': 'Sunday 23 August, 14:10 · next coupon is Amazonia on Friday 28 August',
              'band': [['Bonds held', '10,450c', 'face value across four issuers', 'n'],
                       ['Coupon income',
                        '135.75c',
                        'a month, paid on each issuer filing date',
                        'g'],
                       ['Bonds issued', '15,000c', 'GreyHames, two series', 'w'],
                       ['Owed to you', '2,850c', 'BNL series B matures Mon 31 Aug', 'g']],
              'blocks': [{'h2': 'Due in the next ten days',
                          'ac': 1,
                          'c': ['Due', 'Item', 'Counterparty', 'Amount#', 'Note'],
                          'r': [['Wed 26 Aug',
                                 'Loan repayment',
                                 'Overhaul-A-Ledger',
                                 'l|1,150c out',
                                 'm|five payments left'],
                                ['Fri 28 Aug',
                                 'Coupon',
                                 'Amazonia, 2026 series',
                                 'g|48.00c in',
                                 'm|1.2% a month'],
                                ['Fri 28 Aug',
                                 'Coupon',
                                 'Sancta, 2026 series',
                                 'g|36.00c in',
                                 'm|1.2% a month'],
                                ['Sat 29 Aug',
                                 'Coupon paid',
                                 'GreyHames, series A',
                                 'l|90.00c out',
                                 'm|paid before dividends'],
                                ['Mon 31 Aug',
                                 'Principal returned',
                                 'BNL, series B',
                                 'g|2,850c in',
                                 'm|matures at par']],
                          'n': 'Five items, soonest first. Coupons pay before dividends.'},
                         {'h2': 'Bonds held',
                          'c': ['Issuer',
                                'Series',
                                'Face#',
                                'Coupon#',
                                'Rate#',
                                'Matures',
                                'Issuer grade'],
                          'r': [['Amazonia',
                                 '2026 series',
                                 '4,000c',
                                 '48.00c a month',
                                 '1.2% a month',
                                 'Wed 4 Nov',
                                 'AA'],
                                ['Sancta',
                                 '2026 series',
                                 '3,000c',
                                 '36.00c a month',
                                 '1.2% a month',
                                 'Fri 2 Oct',
                                 'AA'],
                                ['BNL',
                                 'Series B',
                                 '2,850c',
                                 '42.75c a month',
                                 '1.5% a month',
                                 'Mon 31 Aug',
                                 'A'],
                                ['Toolshop',
                                 'Series A',
                                 '600c',
                                 '9.00c a month',
                                 '1.5% a month',
                                 'Tue 15 Sep',
                                 'BBB']],
                          'n': 'Four holdings, 10,450c face, soonest maturity first. Issuers must '
                               'be BBB or better to issue at all.'},
                         {'h2': 'Bonds GreyHames has issued',
                          'own': 1,
                          'c': ['Series',
                                'Face#',
                                'Coupon#',
                                'Rate#',
                                'Matures',
                                'Held by',
                                'Status'],
                          'r': [['Series A',
                                 '10,000c',
                                 '90.00c a month',
                                 '0.9% a month',
                                 'Fri 27 Nov',
                                 'six holders',
                                 'Current'],
                                ['Series B',
                                 '5,000c',
                                 '50.00c a month',
                                 '1.0% a month',
                                 'Wed 30 Sep',
                                 'three holders',
                                 'Current']],
                          'n': 'Two series, 15,000c face, 140.00c of coupons a month.'},
                         {'h2': 'Debt owed by GreyHames',
                          'own': 1,
                          'bal': [['GEX principal',
                                   '12,000c',
                                   'shares cancelled and reissued as principal, serviced before '
                                   'dividends'],
                                  ['Bonds outstanding', '15,000c', 'two series']],
                          'tot': ['Owed', '27,000c'],
                          'lk': 'How the payout order works'},
                         {'h2': 'Loans available to you',
                          'bal': [['Credit limit', '26,000c', 'earned, not a share of holdings'],
                                  ['Less drawn', '8,000c', '1.5% a week']],
                          'tot': ['Available to borrow', '18,000c'],
                          'lk': 'How the limit is earned'}]},
 'orders': {'d': 'work',
            'title': 'Orders',
            'asof': 'Sunday 23 August, 14:10 · employees get the first 45 minutes on every order',
            'band': [['Open orders', '6', '4,666c committed'],
                     ['Held in orders, bids and bets',
                      '12,400c',
                      'the balance sits in auction bids and bets'],
                     ['Claimed today', '3', 'two in progress, one delivered'],
                     ['Employee priority', '45 minutes', 'on the Employee role']],
            'blocks': [{'h2': 'Open orders',
                        'ac': 1,
                        'c': ['Item',
                              'Market',
                              'Quantity',
                              'Pay#',
                              'Total#',
                              'Claimed by',
                              'Status'],
                        'r': [['Blaze rod',
                               'Nether market',
                               '2 stacks',
                               '180c per stack',
                               '360c',
                               'm|unclaimed',
                               'w|Employees only, 8 minutes left'],
                              ['Iron ingot',
                               'Toolshop',
                               '8 stacks',
                               '42c per stack',
                               '336c',
                               'm|unclaimed',
                               'w|Employees only, 31 minutes left'],
                              ['Glass pane',
                               'ViridianMarket',
                               '320 pieces',
                               '1.4c per piece',
                               '448c',
                               'm|unclaimed',
                               'g|Open to all'],
                              ['Redstone dust',
                               'GreyHames',
                               '6 stacks',
                               '96c per stack',
                               '576c',
                               'Kael',
                               'In progress'],
                              ['Enchanted book',
                               'GreyHames',
                               '9 pieces',
                               '290c per piece',
                               '2,610c',
                               'Mira',
                               'In progress'],
                              ['Oak log',
                               'Farmstead Co',
                               '12 stacks',
                               '28c per stack',
                               '336c',
                               'Bram',
                               'Delivered, awaiting payment']],
                        'n': 'Six open orders, 4,666c committed. A stack is 64 pieces and pay is '
                             'per piece unless the order says per stack.'},
                       {'h2': 'Filled this week',
                        'c': ['Filled', 'Item', 'Market', 'Worker', 'Quantity', 'Paid#'],
                        'r': [['Sat 22 Aug',
                               'Diamond',
                               'GreyHames',
                               'Kael',
                               '3 stacks',
                               'g|1,280c'],
                              ['Fri 21 Aug',
                               'Lapis lazuli',
                               'Amazonia',
                               'Mira',
                               '5 stacks',
                               'g|1,050c'],
                              ['Thu 20 Aug',
                               'Prismarine',
                               'NauticalMarket',
                               'Bram',
                               '12 stacks',
                               'g|768c'],
                              ['Wed 19 Aug',
                               'Cocoa beans',
                               'Sancta',
                               'Kael',
                               '640 pieces',
                               'g|512c']],
                        'n': 'Four most recent, this week.'}],
            'dock': {'kind': 'Order draft, not posted',
                     'title': 'Blaze rod for GreyHames',
                     'pairs': [['Quantity', '4 stacks'],
                               ['Pay', '180c per stack'],
                               ['Total', '720c'],
                               ['Visibility', 'Employees first, 45 minutes']],
                     'note': 'A stack is 64 pieces. The total is held from your wallet until the '
                             'order is filled or withdrawn.',
                     'btns': [['Discard', 's'], ['Post the order', 'p']]}},
 'auctions': {'d': 'auctions',
              'title': 'Auctions',
              'asof': 'Sunday 23 August, 14:10 · three lots live, the soonest closing in under a '
                      'minute',
              'band3': 1,
              'band': [['Live lots', '3', 'one you lead, one outbid'],
                       ['Held in bids', '6,200c', 'released when a lot closes'],
                       ['Closing next', 'T|48', 'Netherite upgrade template, you lead']],
              'blocks': [{'h2': 'Live lots',
                          'ac': 1,
                          'c': ['Lot',
                                'Seller',
                                'Current bid#',
                                'Your bid#',
                                'Bids#',
                                'Closes',
                                'Your position'],
                          'r': [['Netherite upgrade template',
                                 'Sancta',
                                 '4,800c',
                                 '4,800c',
                                 '14',
                                 'T|48',
                                 'g|You lead'],
                                ['Mending book',
                                 'GreyHames',
                                 '2,900c',
                                 '1,400c',
                                 '9',
                                 'T|276',
                                 'l|Outbid'],
                                ['Elytra',
                                 'Enderport',
                                 '5,200c',
                                 'm|—',
                                 '21',
                                 'T|7350',
                                 'm|No bid']],
                          'n': 'Three live lots, soonest close first. A bid is held from your '
                               'wallet until the lot closes.'},
                         {'h2': 'Sold this month',
                          'own': 1,
                          'c': ['Lot', 'Buyer', 'Sold for#', 'Fee#', 'Net to GreyHames#', 'Closed'],
                          'r': [['Beacon',
                                 'Amazonia',
                                 '9,400c',
                                 'l|470c',
                                 'g|8,930c',
                                 'Fri 21 Aug'],
                                ['Totem of undying',
                                 'Yulen',
                                 '3,600c',
                                 'l|180c',
                                 'g|3,420c',
                                 'Wed 19 Aug'],
                                ['Shulker box, 8',
                                 'V Tech',
                                 '2,240c',
                                 'l|112c',
                                 'g|2,128c',
                                 'Mon 17 Aug'],
                                ['Trident',
                                 'Nether market',
                                 '1,800c',
                                 'l|90c',
                                 'g|1,710c',
                                 'Sat 15 Aug']],
                          'n': 'Four lots with GreyHames as seller, 16,188c net. The fee is 5% of '
                               'the closing bid.'},
                         {'h2': 'Your bids',
                          'bal': [['Leading, Netherite upgrade template',
                                   '4,800c',
                                   'closes in under a minute'],
                                  ['Outbid, Mending book',
                                   '1,400c',
                                   'released when the lot closes']],
                          'tot': ['Held in bids', '6,200c']}]},
 'work': {'d': 'work',
          'title': 'Work',
          'asof': 'Sunday 23 August, 14:10 · seven jobs open across seven markets',
          'band': [['Open jobs', '7', 'three restricted to employees'],
                   ['Claims waiting on you', '3', '1,860c owed', 'w'],
                   ['Paid this month', '8,540c', 'three workers'],
                   ['Employee priority', '45 minutes', 'on the Employee role']],
          'blocks': [{'h2': 'Claims waiting on you',
                      'ac': 1,
                      'own': 1,
                      'c': ['Claimed', 'Worker', 'Item', 'Quantity', 'Pay#', 'Delivered', '#'],
                      'r': [['Sat 22 Aug',
                             'Kael',
                             'Redstone dust for GreyHames',
                             '4 stacks at 155c per stack',
                             '620c',
                             'Sat 22 Aug',
                             'k|Approve'],
                            ['Fri 21 Aug',
                             'Mira',
                             'Enchanted book for GreyHames',
                             '4 pieces at 185c per piece',
                             '740c',
                             'Fri 21 Aug',
                             'k|Approve'],
                            ['Thu 20 Aug',
                             'Bram',
                             'Oak log for Farmstead Co',
                             '20 stacks at 25c per stack',
                             '500c',
                             'Thu 20 Aug',
                             'k|Approve']],
                      'n': 'Three claims, 1,860c owed. Approving pays the worker from the market '
                           'vault.'},
                     {'h2': 'Open jobs',
                      'c': ['Item', 'Market', 'Quantity', 'Pay#', 'Total#', 'Who can claim'],
                      'r': [['Blaze rod',
                             'Nether market',
                             '2 stacks',
                             '180c per stack',
                             '360c',
                             'w|Employees only, 8 minutes left'],
                            ['Prismarine',
                             'NauticalMarket',
                             '12 stacks',
                             '64c per stack',
                             '768c',
                             'w|Employees only, 22 minutes left'],
                            ['Iron ingot',
                             'Toolshop',
                             '8 stacks',
                             '42c per stack',
                             '336c',
                             'w|Employees only, 31 minutes left'],
                            ['Lapis lazuli',
                             'Amazonia',
                             '5 stacks',
                             '210c per stack',
                             '1,050c',
                             'g|Open to all'],
                            ['Glass pane',
                             'ViridianMarket',
                             '320 pieces',
                             '1.4c per piece',
                             '448c',
                             'g|Open to all'],
                            ['Spruce log',
                             'Farmstead Co',
                             '16 stacks',
                             '26c per stack',
                             '416c',
                             'g|Open to all'],
                            ['Cocoa beans',
                             'Sancta',
                             '640 pieces',
                             '0.8c per piece',
                             '512c',
                             'g|Open to all']],
                      'n': 'Seven open jobs across seven markets, restricted first. A stack is 64 '
                           'pieces and pay is per piece unless the order says per stack.'},
                     {'h2': 'Pay this month',
                      'own': 1,
                      'bal': [['Kael, 34 orders', '4,220c', '620c claimed and waiting'],
                              ['Mira, 21 orders', '2,610c', '740c claimed and waiting'],
                              ['Bram, 12 orders', '1,710c', '500c claimed and waiting']],
                      'tot': ['Paid', '8,540c']}]},
 'lands': {'d': 'lands',
           'title': 'Claims',
           'asof': 'Sunday 23 August, 14:10 · four claims listed for sale',
           'band3': 1,
           'band': [['Claims held', '2', '36 chunks in total'],
                    ['Bought for', '32,400c', 'across two claims'],
                    ['Listed for sale', '4', '14,000c to 38,000c']],
           'blocks': [{'h2': 'Your claims',
                       'ac': 1,
                       'c': ['Claim', 'Continent', 'Chunks#', 'Use', 'Bought for#'],
                       'r': [['Market row', 'Central', '12', 'GreyHames stall', '12,400c'],
                             ['Nether hub',
                              'Nether reach',
                              '24',
                              'GreyHames warehouse',
                              '20,000c']],
                       'n': 'Two claims, 36 chunks, 32,400c paid. A claim is owned outright and '
                            'transfers with the build on it.'},
                      {'h2': 'For sale',
                       'c': ['Claim', 'Continent', 'Chunks#', 'Price#', 'Seller', 'Listed'],
                       'r': [['Irongate row', 'Central', '16', '14,000c', 'Sancta', 'Fri 21 Aug'],
                             ['Basalt quarter',
                              'Nether reach',
                              '32',
                              '26,500c',
                              'Enderport',
                              'Wed 19 Aug'],
                             ['Coastal ridge',
                              'Westmarch',
                              '96',
                              '38,000c',
                              'NauticalMarket',
                              'Mon 17 Aug'],
                             ['Farm belt',
                              'Greenreach',
                              '48',
                              '19,200c',
                              'Farmstead Co',
                              'Sat 15 Aug']],
                       'n': 'Four claims for sale, most recent listing first. A whole city sits '
                            'inside one claim.',
                       'lk': 'How claims transfer'}]},
 'messages': {'d': 'hub',
              'title': 'Messages',
              'asof': 'Three unread · latest Saturday 22 August',
              'blocks': [{'h2': 'Unread',
                          'ac': 1,
                          'c': ['From', 'Subject', 'Received'],
                          'r': [['Kael',
                                 'Redstone claim delivered, 4 stacks at 155c per stack',
                                 'Sat 22 Aug, 20:40'],
                                ['Overhaul-A-Ledger',
                                 'Repayment of 1,150c due Wednesday 26 August',
                                 'Fri 21 Aug, 09:00'],
                                ['Amazonia',
                                 'Coupon of 48.00c pays Friday 28 August',
                                 'Fri 21 Aug, 08:15']],
                          'n': 'Three unread, newest first.'},
                         {'h2': 'Earlier',
                          'c': ['From', 'Subject', 'Received'],
                          'r': [['Mira',
                                 'Enchanted book claim delivered, 4 pieces',
                                 'Fri 21 Aug, 18:05'],
                                ['Sancta',
                                 'You lead the Netherite upgrade template at 4,800c',
                                 'Fri 21 Aug, 12:30'],
                                ['Bram', 'Oak log claim delivered, 20 stacks', 'Thu 20 Aug, 17:50'],
                                ['Abex Tech',
                                 'Savings interest of 313.80c paid, 0.20% a week',
                                 'Sun 17 Aug, 00:05'],
                                ['Farmstead Co',
                                 'August report missed, grade dropped to C',
                                 'Fri 14 Aug, 23:59'],
                                ['Toolshop', 'Series A coupon of 9.00c paid', 'Mon 11 Aug, 08:00']],
                          'n': 'Six of 42 earlier messages, newest first.'}]},
 'history': {'d': 'hub',
             'title': 'History',
             'asof': 'Sunday 23 August, 14:10 · 46 entries this month',
             'band3': 1,
             'band': [['Entries this month', '46', 'eight this week'],
                      ['Money in', '12,480c', 'dividends, coupons and interest', 'g'],
                      ['Money out', '9,240c', 'shares, bids, stakes and repayments', 'l']],
             'blocks': [{'h2': 'This week',
                         'ac': 1,
                         'c': ['Date', 'Entry', 'Counterparty', 'In#', 'Out#'],
                         'r': [['Sat 22 Aug',
                                'Savings interest, 0.20% a week',
                                'Abex Tech',
                                'g|313.80c',
                                'm|—'],
                               ['Sat 22 Aug',
                                'Dividend, 0.05c a share',
                                'Amazonia',
                                'g|44.00c',
                                'm|—'],
                               ['Fri 21 Aug',
                                'Bid placed, Netherite upgrade template',
                                'Sancta',
                                'm|—',
                                'l|4,800c'],
                               ['Fri 21 Aug', 'Coupon, 1.2% a month', 'Sancta', 'g|36.00c', 'm|—'],
                               ['Thu 20 Aug',
                                'Loan repayment, five left',
                                'Overhaul-A-Ledger',
                                'm|—',
                                'l|1,150c'],
                               ['Wed 19 Aug',
                                'Bet settled, V Tech net above 24,000c',
                                'Abex Tech',
                                'g|655.00c',
                                'm|—'],
                               ['Wed 19 Aug',
                                'Shares bought, 538 at 1.95c',
                                'Toolshop',
                                'm|—',
                                'l|1,049.10c'],
                               ['Tue 18 Aug', 'Dividend, 0.03c a share', 'BNL', 'g|48.00c', 'm|—']],
                         'n': 'Eight entries this week, newest first.',
                         'lk': 'Export the month'}]}}
